remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have onee


title: [The Clue2solve Oss Home]
description: [The Clue2solve Oss Home]
